[development]
address = "localhost"
port = 4000
workers = 16
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 3003
workers = 4
log = "critical"
limits = { forms = 32768 }